### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by gowrav** [WebReflection/benja#10] opened 2017-04-23 16:22 UTC
Support for 
> Odroid C2
> Nano Pi K2

**Comment by WebReflection** [comment] 2017-04-23 17:40
The problem is Electron, AFAIK not built for ARM64 yet, otherwise it'd be there already

**Comment by gowrav** [comment] 2017-04-27 08:40
Thanks... lets keep this open for a resolve..

**Comment by WebReflection** [comment] 2017-04-27 08:47
Nothing I can resolve here though.

**Comment by zeke** [comment] 2017-06-14 04:45
👋 I'm on the Electron team. We are hoping to have an ARM64 build soon. I will try to remember to report back here when we do.

**Comment by WebReflection** [comment] 2017-06-29 22:19
@zeke did you forget to report? :smiley: 

just asking for a possible ETA so I can either close or wait and publish a new ISO for Pi3, thanks

**Comment by zeke** [comment] 2017-06-29 22:58
> did you forget to report?

Didn't forget. It just doesn't exist yet.

**Comment by WebReflection** [comment] 2017-06-29 23:10
OK, closing for maintenance sake but please do notify me/us/here if there's any progress, thank you!

**Closed as completed by WebReflection** 2017-06-29 23:10 UTC
